cwdb_website/authapp/urls.py
from django.urls import path,reverse_lazy

from django.conf import settings
from django.conf.urls.static import static
from . import views

from .views import UserProfileView,EditProfileView,CustomLoginView
app_name = 'authapp'
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

urlpatterns = [
    #HomePage
    path('',views.index,name='index'),
    path('proposal/list/', views.proposal_list, name='proposal_list'),
    path('beneficiary-data/', views.beneficiary_data_table, name='beneficiary_data_table'),
    path('iwdp/', views.iwdp_view, name='iwdp_view'),
    path('wms-data/',views.wms_scheme_view,name='wms_scheme_view'),
    path('wps-data/',views.wps_scheme_view,name='wps_scheme_view'),
    path('pwds-data/',views.pwds_scheme_view,name='pwds_scheme_view'),
    path('hrdpa-data/',views.hrdpa_scheme_view,name='hrdpa_scheme_view'),
    path('admin_Expenses',views.admin_exp_view,name='admin_exp_view'),
     
    path('signup/', views.signup, name='register'),
    
    
    path('notifications/', views.index_notification_view, name='index_notification_view'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),
    # path('login/',user_login,name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/submit_proposal/', views.submit_proposal, name='submit_proposal'),
    path('dashboard/proposal_detail/<int:proposal_id>/', views.proposal_detail, name='proposal_detail'),
    path('dashboard/proposal_list/', views.proposal_list, name='proposal_list'),
    path('dashboard/admin_proposal_list/', views.admin_proposal_list, name='admin_proposal_list'),
    path('dashboard/admin_proposal_detail/<int:proposal_id>/', views.admin_proposal_detail, name='admin_proposal_detail'),
    path('dashboard/proposal_status/', views.proposal_status, name='proposal_status'),
    path('dashboard/proposal_documents/', views.proposal_documents, name='proposal_documents'),
     path('dashboard/sanction-letters/<str:proposal_id>/', views.sanction_letters_view, name='sanction_letters_view'),
    path('dashboard/inspection-letters/<str:proposal_id>/', views.inspection_letters_view, name='inspection_letters_view'),
    path('dashboard/form-submitted/', views.form_submitted_successfully, name='form_submitted_successfully'),

    # path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('login/', CustomLoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='authapp:index'), name='logout'),
    path('admin/logout/',LogoutView.as_view(next_page='authapp:index'), name='logout'),
     path('dashboard/change-password/', PasswordChangeView.as_view(), name='change_password'),
    #proposal admin urls
    path('admin/submit_approval/<str:proposal_id>/', views.submit_approval, name='submit_approval'),
path('admin/submit_installment_sanction_letter/<str:proposal_id>/', views.submit_installment_sanction_letter, name='submit_installment_sanction_letter'),
 path('admin/submit_inspection_report/<str:proposal_id>/', views.submit_inspection_letter, name='submit_inspection_report'),

    # Password Reset URLs
    path('dashboard/forgot-password/', PasswordResetView.as_view(), name='forgot_password'),
    path('dashboard/5/password/', PasswordResetView.as_view(), name='forgot_password'),
    path('dashboard/forgot-password/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('dashboard/reset-password/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('dashboard/reset-password/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # #progress report urls 
    path('dashboard/progress_report/', views.progress_report, name='progress_report'),
    #wms subcomponents
    path('dashboard/revolving_fund_progress_report/<str:proposal_unique_id>/', views.revolving_fund_progress_report, name='revolving_fund_progress_report'),
    path('dashboard/eportal/<str:proposal_unique_id>/', views.eportal_progress_report, name='eportal_progress_report'),
    path('dashboard/selfhelpgroup_report/<str:proposal_unique_id>/', views.selfhelpgroup_report, name='selfhelpgroup_report'),
    path('dashboard/buyersellerexpo_report/<str:proposal_unique_id>/', views.buyersellerexpo_report, name='buyersellerexpo_report'),
    path('dashboard/infrastructuredevelopment_report/<str:proposal_unique_id>/', views.infrastructuredevelopment_report, name='infrastructuredevelopment_report'),
    path('dashboard/woolen_expo/<str:proposal_unique_id>/', views.woolen_expo, name='woolen_expo'),
    path('dashboard/woolen_expo_hiring/<str:proposal_unique_id>/', views.woolen_expo_hiring, name='woolen_expo_hiring'),
    #wps subcomponent
    path('dashboard/cfc_progress_report/<str:proposal_unique_id>/', views.cfc_progress_report, name='cfc_progress_report'),
    path('dashboard/sheep_shearing_machining/<str:proposal_unique_id>/', views.sheep_shearing_machining, name='sheep_shearing_machining'),
    path('dashboard/equipment/<str:proposal_unique_id>/', views.equipment, name='equipment'),
    path('dashboard/small_tools_distribution/<str:proposal_unique_id>/', views.small_tools_distribution, name='small_tools_distribution'),
   # hrd subcomponent
    path('dashboard/short_term_programme/<str:proposal_unique_id>/', views.short_term_programme, name='short_term_programme'),
    path('dashboard/onsite_training_progress_report/<str:proposal_unique_id>/', views.onsite_training_progress_report, name='onsite_training_progress_report'),
    path('dashboard/shearing_machine_training_report/<str:proposal_unique_id>/', views.shearing_machine_training_report, name='shearing_machine_training_report'),
    path('dashboard/rd_report/<str:proposal_unique_id>/', views.rd_report, name='rd_report'),
    path('dashboard/domestic_meeting_report/<str:proposal_unique_id>/', views.domestic_meeting_report, name='domestic_meeting_report'),
    path('dashboard/organising_seminar_report/<str:proposal_unique_id>/', views.organising_seminar_report, name='organising_seminar_report'),
    path('dashboard/wool_survey_report/<str:proposal_unique_id>/', views.wool_survey_report, name='wool_survey_report'),
    path('dashboard/wool_testing_lab_report/<str:proposal_unique_id>/', views.wool_testing_lab_report, name='wool_testing_lab_report'),
    path('dashboard/publicity_monitoring_report/<str:proposal_unique_id>/', views.publicity_monitoring_report, name='publicity_monitoring_report'),
    #pwds subcomponent
    path('dashboard/pashmina_revolving_fund_progress_report/<str:proposal_unique_id>/', views.pashmina_revolving_fund_progress_report, name='pashmina_revolving_fund_progress_report'),
    path('dashboard/pashmina_cfc_report/<str:proposal_unique_id>/', views.pashmina_cfc_report, name='pashmina_cfc_report'),
    path('dashboard/shelter_shed_report/<str:proposal_unique_id>/', views.shelter_shed_report, name='shelter_shed_report'),
    path('dashboard/portable_tent_report/<str:proposal_unique_id>/', views.portable_tent_report, name='portable_tent_report'),
    path('dashboard/predator_proof_lights_report/<str:proposal_unique_id>/', views.predator_proof_lights_report, name='predator_proof_lights_report'),
    path('dashboard/testing_equipment_report/<str:proposal_unique_id>/', views.testing_equipment_report, name='testing_equipment_report'),
    path('dashboard/showroom_development_report/<str:proposal_unique_id>/', views.showroom_development_report, name='showroom_development_report'),
    path('dashboard/fodder_land_development_report/<str:proposal_unique_id>/', views.fodder_land_development_report, name='fodder_land_development_report'),
    #admin
    # urls.py

# path('admin/view_progress_report/<str:proposal_id>/', views.view_progress_report, name='view_progress_report'),
    
#notifications
# path('dashboard/show-notifications/', views.show_notifications, name='show_notifications'),
path('dashboard/show-all-notifications/', views.show_all_notifications, name='show_all_notifications'),
path('dashboard/profile/', UserProfileView.as_view(), name='user_profile'),
path('dashboard/profile/edit/', EditProfileView.as_view(), name='edit_profile'),
# path('dashboard/updated', views.show_notifications, name='show_new_notifications'),
#staff dashboard
path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
path('staff_dashboard/all-proposals/', views.all_proposal_details, name='all_proposal_details'),
path('submit-approval/<str:proposal_id>/', views.submit_approval, name='submit_approval'),
path('generate-summary/<str:proposal_id>/', views.summ_report, name='summ_report'),

#API url
path('apicall/', views.proposal_api),
    
    # Add more patterns as needed

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cwdb_website/src/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import include, path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from authapp.views import index
urlpatterns = [
    path('', include('authapp.urls', namespace='authapp')),
    #  (r'^admin/', include(admin.site.urls) ),
    path('admin/', admin.site.urls),
     # Password Reset URLs
    path('dashboard/forgot-password/', PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='forgot_password'),
    path('dashboard/forgot-password/done/', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('dashboard/reset-password/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('dashboard/reset-password/done/', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    #  path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
     path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change_form.html',
        success_url='password_change_done'
    ), name='change_password'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html'
    ), name='password_change_done'),
]

cwdb_website/templates/main/HomePage/base_homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Dashboard{% endblock %}</title>
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
     <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="{% static '/css/index/nucleo-icons.css'%}" rel="stylesheet" />
  
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="{%static '/css/index/material-dashboard.css?v=3.1.0'%}" rel="stylesheet" />
    
     <link rel="stylesheet" href="{% static 'css/index_style.css' %}">
	 <link rel="stylesheet" href="{%static 'css/theme.css'%}">
    <link rel="stylesheet" href="{%static 'css/loopple/loopple.css'%}">  
    <style>
      /* Apply hand cursor to links and buttons */
      a, button {
        cursor: pointer;
      }
    </style>
</head>

<body class="g-sidenav-show  bg-gray-200">
  
  <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header text-center  py-3 d-flex align-items-center justify-content-center">
        <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
        <a class="navbar-brand m-0" href="#" target="_blank">
            <h4 class="font-weight-bold text-white mb-0">MIS Portal</h4>
        </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-white active bg-gradient-primary" href="{%url 'authapp:index' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">dashboard</i>
            </div>
            <span class="nav-link-text ms-1">Dashboard</span>
          </a>
        </li>
        
       
       
        
        <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'authapp:index_notification_view' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">notifications</i>
            </div>
            <span class="nav-link-text ms-1">Notifications</span>
          </a>
        </li>
        
      
        <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'authapp:login' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">login</i>
            </div>
            <span class="nav-link-text ms-1">Sign In</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'authapp:register' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">assignment</i>
            </div>
            <span class="nav-link-text ms-1">Sign Up</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " href="http://3.111.35.175/drupal/">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">arrow_back</i>
            </div>
            <span class="nav-link-text ms-1">Go Back to Website</span>
          </a>
        </li>
      </ul>
    </div>
    <div class="sidenav-footer position-absolute w-100 bottom-0 ">
    
  </aside>
  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
      <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Dashboard</li>
          </ol>
          <h6 class="font-weight-bolder mb-0">Dashboard</h6>
        </nav>
        
        <ul class="navbar-nav  justify-content-end">
   
          <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
            <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
              <div class="sidenav-toggler-inner">
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
              </div>
            </a>
          </li>
          <li class="nav-item px-3 d-flex align-items-center">
            <a href="javascript:;" class="nav-link text-body p-0">
              <i class="fa fa-cog fixed-plugin-button-nav cursor-pointer"></i>
            </a>
          </li>
          <li class="nav-item dropdown pe-2 d-flex align-items-center">
            <a href="{% url 'authapp:index_notification_view' %}" class="nav-link text-body p-0"  >
              <i class="fa fa-bell cursor-pointer"></i>
            </a>
      
           
          </li>
          <li class="nav-item d-flex align-items-center">
            <a href="{% url 'authapp:login' %}" class="nav-link text-body font-weight-bold px-0">
              <i class="fa fa-user me-sm-1"></i>
              
              <span class="d-sm-inline d-none">Sign In</span>
              
            </a>
          </li>
        </ul>
        </div>
      </div>
    </nav>
    <!-- End Navbar -->
    <div class="container-fluid py-4">
    {% block content %}{% endblock %}
    </div>
    <div class="fixed-plugin">
        <a class="fixed-plugin-button text-dark position-fixed px-3 py-2">
          <i class="material-icons py-2">settings</i>
        </a>
        <div class="card shadow-lg">
          <div class="card-header pb-0 pt-3">
            <div class="float-start">
              <h5 class="mt-3 mb-0">Dashboard UI Configurator</h5>
              <p>See our dashboard options.</p>
            </div>
            <div class="float-end mt-4">
              <button class="btn btn-link text-dark p-0 fixed-plugin-close-button">
                <i class="material-icons">clear</i>
              </button>
            </div>
            <!-- End Toggle Button -->
          </div>
          <hr class="horizontal dark my-1">
          <div class="card-body pt-sm-3 pt-0">
            <!-- Sidebar Backgrounds -->
            <div>
              <h6 class="mb-0">Sidebar Colors</h6>
            </div>
            <a href="javascript:void(0)" class="switch-trigger background-color">
              <div class="badge-colors my-2 text-start">
                <span class="badge filter bg-gradient-primary active" data-color="primary" onclick="sidebarColor(this)"></span>
                <span class="badge filter bg-gradient-dark" data-color="dark" onclick="sidebarColor(this)"></span>
                <span class="badge filter bg-gradient-info" data-color="info" onclick="sidebarColor(this)"></span>
                <span class="badge filter bg-gradient-success" data-color="success" onclick="sidebarColor(this)"></span>
                <span class="badge filter bg-gradient-warning" data-color="warning" onclick="sidebarColor(this)"></span>
                <span class="badge filter bg-gradient-danger" data-color="danger" onclick="sidebarColor(this)"></span>
              </div>
            </a>
            <!-- Sidenav Type -->
            <div class="mt-3">
              <h6 class="mb-0">Sidenav Type</h6>
              <p class="text-sm">Choose between 2 different sidenav types.</p>
            </div>
            <div class="d-flex">
              <button class="btn bg-gradient-dark px-3 mb-2 active" data-class="bg-gradient-dark" onclick="sidebarType(this)">Dark</button>
              <button class="btn bg-gradient-dark px-3 mb-2 ms-2" data-class="bg-transparent" onclick="sidebarType(this)">Transparent</button>
              <button class="btn bg-gradient-dark px-3 mb-2 ms-2" data-class="bg-white" onclick="sidebarType(this)">White</button>
            </div>
            <p class="text-sm d-xl-none d-block mt-2">You can change the sidenav type just on desktop view.</p>
            <!-- Navbar Fixed -->
            <div class="mt-3 d-flex">
              <h6 class="mb-0">Navbar Fixed</h6>
              <div class="form-check form-switch ps-0 ms-auto my-auto">
                <input class="form-check-input mt-1 ms-auto" type="checkbox" id="navbarFixed" onclick="navbarFixed(this)">
              </div>
            </div>
            <hr class="horizontal dark my-3">
            <div class="mt-2 d-flex">
              <h6 class="mb-0">Light / Dark</h6>
              <div class="form-check form-switch ps-0 ms-auto my-auto">
                <input class="form-check-input mt-1 ms-auto" type="checkbox" id="dark-version" onclick="darkMode(this)">
              </div>
            </div>
            <hr class="horizontal dark my-sm-4">
           
            
          </div>
        </div>
      </div>
      <!--   Core JS Files   -->
      <script src="{%static 'javascript/index/js/core/popper.min.js'%}"></script>
      <script src="{%static 'javascript/index/js/core/bootstrap.min.js'%}"></script>
      <script src="{%static 'javascript/index/js/plugins/perfect-scrollbar.min.js'%}"></script>
      <script src="{%static 'javascript/indexjs/plugins/smooth-scrollbar.min.js'%}"></script>
      <script src="{%static 'javascript/index/js/plugins/chartjs.min.js'%}"></script>
      <script src="{%static 'javascript/index/js/material-dashboard.min.js' %}"></script>
       
</body>

</html>

cwdb_website/templates/main/HomePage/index_notifications.html
{%extends 'base_index.html'%}
{% load static %}
{% block title %}Notifications{% endblock %}
{%block content%}
<style>
  /* Custom CSS */
  .light-color {
      color: #f8f9fa; /* Light color, adjust as needed */
  }

  .custom-font {
      font-family: Arial, Helvetica, sans-serif; /* Standard font stack */
  }

  .card-header {
      /* Change the background color of the card header */
      color: white; /* Text color */
  }

  

  

  .form-check-label {
      font-weight: normal; /* Remove bold font weight from the label */
  }

  .forgot-password a {
      color: #757575; /* Change the color of the forgot password link */
      text-decoration: none; /* Remove underline from the link */
  }

  .forgot-password a:hover {
      color: #3f51b5; /* Change color on hover */
  }

  .notification-card {
    background-color: #fff;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    border-radius: 8px;
    margin-bottom: 20px;
    padding: 20px;
}

.created-at-card {
    background-color: #f9f9f9;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    border-radius: 8px;
    margin-bottom: 10px;
    padding: 10px;
    font-size: 0.9em;
}

.no-data {
    text-align: center;
    color: #777;
    padding: 20px;
}

</style>



   
  <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header text-center  py-3 d-flex align-items-center justify-content-center">
        <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
        <a class="navbar-brand m-0" href="#" target="_blank">
            <h4 class="font-weight-bold text-white mb-0">MIS Portal</h4>
        </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-white " href="{%url 'authapp:index' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">dashboard</i>
            </div>
            <span class="nav-link-text ms-1">Dashboard</span>
          </a>
        </li>
        
       
       
        
        <li class="nav-item">
          <a class="nav-link text-white active bg-gradient-primary" href="{% url 'authapp:index_notification_view' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">notifications</i>
            </div>
            <span class="nav-link-text ms-1">Notifications</span>
          </a>
        </li>
        
      
        <li class="nav-item">
          <a class="nav-link text-white  " href="{% url 'authapp:login' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">login</i>
            </div>
            <span class="nav-link-text ms-1">Sign In</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'authapp:register' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">assignment</i>
            </div>
            <span class="nav-link-text ms-1">Sign Up</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " href="http://3.111.35.175/drupal/">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">arrow_back</i>
            </div>
            <span class="nav-link-text ms-1">Go Back to Website</span>
          </a>
        </li>
      </ul>
    </div>
    <div class="sidenav-footer position-absolute w-100 bottom-0 ">
    
  </aside>
  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
      <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Notifications</li>
          </ol>
          <h6 class="font-weight-bolder mb-0">Notifications</h6>
        </nav>
        <ul class="navbar-nav  justify-content-end">
   
          <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
            <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
              <div class="sidenav-toggler-inner">
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
              </div>
            </a>
          </li>
          <li class="nav-item px-3 d-flex align-items-center">
            <a href="javascript:;" class="nav-link text-body p-0">
              <i class="fa fa-cog fixed-plugin-button-nav cursor-pointer"></i>
            </a>
          </li>
          <li class="nav-item dropdown pe-2 d-flex align-items-center">
            <a href="{% url 'authapp:index_notification_view' %}" class="nav-link text-body p-0" >
              <i class="fa fa-bell cursor-pointer"></i>
            </a>
      
           
          </li>
          <li class="nav-item d-flex align-items-center">
            <a href="{% url 'authapp:login' %}" class="nav-link text-body font-weight-bold px-0">
              <i class="fa fa-user me-sm-1"></i>
              
              <span class="d-sm-inline d-none">Sign In</span>
              
            </a>
          </li>
        </ul>
          
        </div>
      </div>
    </nav>
    <!-- End Navbar -->
    <div class="container-fluid py-4">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-primary text-white card-text-center">
                        <h2 class="light-color custom-font">
                            <i class="fas fa-bell me-2"></i> Notifications
                        </h2>
                    </div>
                    <div class="card-body">
                        {% if notifications %}
                            {% for notification in notifications %}
                                <div class="notification-card">
                                    <div class="created-at-card">
                                        <small><strong>{{ notification.created_at|date:"F d, Y H:i a" }}</strong></small>
                                    </div>
                                    <div class="card-content" style="font-size: 1.2em;">
                                        {{ notification.message }}
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="no-data">
                                <p>No notifications found.</p>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
    
            
            
    </div> 
  </main>
  
 
{%endblock%}