cwdb_website/authapp/urls.py
from django.urls import path,reverse_lazy

from django.conf import settings
from django.conf.urls.static import static
from . import views

from .views import UserProfileView,EditProfileView,CustomLoginView
app_name = 'authapp'
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

urlpatterns = [
    #HomePage
    path('',views.index,name='index'),
    path('proposal/list/', views.proposal_list, name='proposal_list'),
    path('beneficiary-data/', views.beneficiary_data_table, name='beneficiary_data_table'),
    path('iwdp/', views.iwdp_view, name='iwdp_view'),
    path('wms-data/',views.wms_scheme_view,name='wms_scheme_view'),
    path('wps-data/',views.wps_scheme_view,name='wps_scheme_view'),
    path('pwds-data/',views.pwds_scheme_view,name='pwds_scheme_view'),
    path('hrdpa-data/',views.hrdpa_scheme_view,name='hrdpa_scheme_view'),
    path('admin_Expenses',views.admin_exp_view,name='admin_exp_view'),
     
    path('signup/', views.signup, name='register'),
    
    
    path('notifications/', views.index_notification_view, name='index_notification_view'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),
    # path('login/',user_login,name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/submit_proposal/', views.submit_proposal, name='submit_proposal'),
    path('dashboard/proposal_detail/<int:proposal_id>/', views.proposal_detail, name='proposal_detail'),
    path('dashboard/proposal_list/', views.proposal_list, name='proposal_list'),
    path('dashboard/admin_proposal_list/', views.admin_proposal_list, name='admin_proposal_list'),
    path('dashboard/admin_proposal_detail/<int:proposal_id>/', views.admin_proposal_detail, name='admin_proposal_detail'),
    path('dashboard/proposal_status/', views.proposal_status, name='proposal_status'),
    path('dashboard/proposal_documents/', views.proposal_documents, name='proposal_documents'),
     path('dashboard/sanction-letters/<str:proposal_id>/', views.sanction_letters_view, name='sanction_letters_view'),
    path('dashboard/inspection-letters/<str:proposal_id>/', views.inspection_letters_view, name='inspection_letters_view'),
    path('dashboard/form-submitted/', views.form_submitted_successfully, name='form_submitted_successfully'),

    # path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('login/', CustomLoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='authapp:index'), name='logout'),
    path('admin/logout/',LogoutView.as_view(next_page='authapp:index'), name='logout'),
     path('dashboard/change-password/', PasswordChangeView.as_view(), name='change_password'),
    #proposal admin urls
    path('admin/submit_approval/<str:proposal_id>/', views.submit_approval, name='submit_approval'),
path('admin/submit_installment_sanction_letter/<str:proposal_id>/', views.submit_installment_sanction_letter, name='submit_installment_sanction_letter'),
 path('admin/submit_inspection_report/<str:proposal_id>/', views.submit_inspection_letter, name='submit_inspection_report'),

    # Password Reset URLs
    path('dashboard/forgot-password/', PasswordResetView.as_view(), name='forgot_password'),
    path('dashboard/5/password/', PasswordResetView.as_view(), name='forgot_password'),
    path('dashboard/forgot-password/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('dashboard/reset-password/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('dashboard/reset-password/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # #progress report urls 
    path('dashboard/progress_report/', views.progress_report, name='progress_report'),
    #wms subcomponents
    path('dashboard/revolving_fund_progress_report/<str:proposal_unique_id>/', views.revolving_fund_progress_report, name='revolving_fund_progress_report'),
    path('dashboard/eportal/<str:proposal_unique_id>/', views.eportal_progress_report, name='eportal_progress_report'),
    path('dashboard/selfhelpgroup_report/<str:proposal_unique_id>/', views.selfhelpgroup_report, name='selfhelpgroup_report'),
    path('dashboard/buyersellerexpo_report/<str:proposal_unique_id>/', views.buyersellerexpo_report, name='buyersellerexpo_report'),
    path('dashboard/infrastructuredevelopment_report/<str:proposal_unique_id>/', views.infrastructuredevelopment_report, name='infrastructuredevelopment_report'),
    path('dashboard/woolen_expo/<str:proposal_unique_id>/', views.woolen_expo, name='woolen_expo'),
    path('dashboard/woolen_expo_hiring/<str:proposal_unique_id>/', views.woolen_expo_hiring, name='woolen_expo_hiring'),
    #wps subcomponent
    path('dashboard/cfc_progress_report/<str:proposal_unique_id>/', views.cfc_progress_report, name='cfc_progress_report'),
    path('dashboard/sheep_shearing_machining/<str:proposal_unique_id>/', views.sheep_shearing_machining, name='sheep_shearing_machining'),
    path('dashboard/equipment/<str:proposal_unique_id>/', views.equipment, name='equipment'),
    path('dashboard/small_tools_distribution/<str:proposal_unique_id>/', views.small_tools_distribution, name='small_tools_distribution'),
   # hrd subcomponent
    path('dashboard/short_term_programme/<str:proposal_unique_id>/', views.short_term_programme, name='short_term_programme'),
    path('dashboard/onsite_training_progress_report/<str:proposal_unique_id>/', views.onsite_training_progress_report, name='onsite_training_progress_report'),
    path('dashboard/shearing_machine_training_report/<str:proposal_unique_id>/', views.shearing_machine_training_report, name='shearing_machine_training_report'),
    path('dashboard/rd_report/<str:proposal_unique_id>/', views.rd_report, name='rd_report'),
    path('dashboard/domestic_meeting_report/<str:proposal_unique_id>/', views.domestic_meeting_report, name='domestic_meeting_report'),
    path('dashboard/organising_seminar_report/<str:proposal_unique_id>/', views.organising_seminar_report, name='organising_seminar_report'),
    path('dashboard/wool_survey_report/<str:proposal_unique_id>/', views.wool_survey_report, name='wool_survey_report'),
    path('dashboard/wool_testing_lab_report/<str:proposal_unique_id>/', views.wool_testing_lab_report, name='wool_testing_lab_report'),
    path('dashboard/publicity_monitoring_report/<str:proposal_unique_id>/', views.publicity_monitoring_report, name='publicity_monitoring_report'),
    #pwds subcomponent
    path('dashboard/pashmina_revolving_fund_progress_report/<str:proposal_unique_id>/', views.pashmina_revolving_fund_progress_report, name='pashmina_revolving_fund_progress_report'),
    path('dashboard/pashmina_cfc_report/<str:proposal_unique_id>/', views.pashmina_cfc_report, name='pashmina_cfc_report'),
    path('dashboard/shelter_shed_report/<str:proposal_unique_id>/', views.shelter_shed_report, name='shelter_shed_report'),
    path('dashboard/portable_tent_report/<str:proposal_unique_id>/', views.portable_tent_report, name='portable_tent_report'),
    path('dashboard/predator_proof_lights_report/<str:proposal_unique_id>/', views.predator_proof_lights_report, name='predator_proof_lights_report'),
    path('dashboard/testing_equipment_report/<str:proposal_unique_id>/', views.testing_equipment_report, name='testing_equipment_report'),
    path('dashboard/showroom_development_report/<str:proposal_unique_id>/', views.showroom_development_report, name='showroom_development_report'),
    path('dashboard/fodder_land_development_report/<str:proposal_unique_id>/', views.fodder_land_development_report, name='fodder_land_development_report'),
    #admin
    # urls.py

# path('admin/view_progress_report/<str:proposal_id>/', views.view_progress_report, name='view_progress_report'),
    
#notifications
# path('dashboard/show-notifications/', views.show_notifications, name='show_notifications'),
path('dashboard/show-all-notifications/', views.show_all_notifications, name='show_all_notifications'),
path('dashboard/profile/', UserProfileView.as_view(), name='user_profile'),
path('dashboard/profile/edit/', EditProfileView.as_view(), name='edit_profile'),
# path('dashboard/updated', views.show_notifications, name='show_new_notifications'),
#staff dashboard
path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
path('staff_dashboard/all-proposals/', views.all_proposal_details, name='all_proposal_details'),
path('submit-approval/<str:proposal_id>/', views.submit_approval, name='submit_approval'),
path('generate-summary/<str:proposal_id>/', views.summ_report, name='summ_report'),

#API url
path('apicall/', views.proposal_api),
    
    # Add more patterns as needed

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cwdb_website/src/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import include, path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from authapp.views import index
urlpatterns = [
    path('', include('authapp.urls', namespace='authapp')),
    #  (r'^admin/', include(admin.site.urls) ),
    path('admin/', admin.site.urls),
     # Password Reset URLs
    path('dashboard/forgot-password/', PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='forgot_password'),
    path('dashboard/forgot-password/done/', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('dashboard/reset-password/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('dashboard/reset-password/done/', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    #  path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
     path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change_form.html',
        success_url='password_change_done'
    ), name='change_password'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html'
    ), name='password_change_done'),
]

cwdb_website/templates/progressReports/progressreport.html
{% extends 'base_dashboard.html' %}

{% block title %}Submit Progress Report{% endblock %}

{% block content %}

<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f4f4f4;
    }

    header {
        background-color: #007BFF;
        color: white;
        text-align: center;
        padding: 1em 0;
        margin-bottom: 20px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;
    }

    h1 {
        margin: 0;
        font-size: 1.5em;
        letter-spacing: 2px;
        text-transform: uppercase;
    }

    table {
        width: 90%;
        margin: 0 auto;
        border-collapse: collapse;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
    }

    th, td {
        border: 1px solid #007BFF;
        padding: 12px;
        text-align: left;
        color: black;
    }

    th {
        background-color: #007BFF;
        color: white;
        font-weight: bold;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    .no-data {
        text-align: center;
        color: #777;
        padding: 20px;
    }

    a {
        text-decoration: none;
        color: #007BFF;
    }
</style>

<header>
    <h1>Submit Progress Report</h1>
</header>


    <table>
        <tr>
            <th>Proposal ID</th>
            <th>Scheme</th>
            <th>SubComponent</th>
            <th>Status</th>
            {% comment %} <th>Project Sanction Letter</th> {% endcomment %}
            <th>Action</th>
        </tr>
        {% if proposals %}
        {% for proposal in proposals %}
            <tr>
                <td>{{ proposal.unique_id }}</td>
                <td>{{ proposal.project_scheme }}</td>
                <td>{{ proposal.scheme_component }}</td>
                <td>{{ proposal.status }}</td>
                {% comment %}  
                <td> {% if proposal.project_sanction_letter %}
                    <a href="{{ proposal.project_sanction_letter.url }}" target="_blank">View Sanction Letter</a>
                {% else %}
                    No Sanction Letter Available
                {% endif %}</td> {% endcomment %}

                <td>
                    {% if proposal.status == 'Approved' %}
                        {% if proposal.scheme_component == '1.Creation of Revolving Fund for Marketing of Raw Wool' %}
                            <a href="{% url 'authapp:revolving_fund_progress_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '2.E-Portal for Marketing Auction of Wool and Development of MIS' %}
                            <a href="{% url 'authapp:eportal_progress_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '3.Financial Assistance for Formation of Wool Producers Societies/Self Help Group(SHGs)' %}
                            <a href="{% url 'authapp:selfhelpgroup_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '4.Organizing Buyers Sellers Meets' %}
                            <a href="{% url 'authapp:buyersellerexpo_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '5.Financial Assistance to Strengthening Infrastructure Required for Wool Marketing' %}
                            <a href="{% url 'authapp:infrastructuredevelopment_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '6.Organization of Domestic Independent Woolen Expo' %}
                            <a href="{% url 'authapp:woolen_expo' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '7.Organizing Domestic Expo on Hiring Stall Basis' %}
                            <a href="{% url 'authapp:woolen_expo_hiring' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '1.Establishing Common Facility Centres (CFCs) for Wool Processing Machines/Facilities' %}
                            <a href="{% url 'authapp:cfc_progress_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '2.Financial Assistance for Sheep Shearing Machines' %}
                            <a href="{% url 'authapp:sheep_shearing_machining' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '3.Financial Assistance for Other Machines and Equipments' %}
                            <a href="{% url 'authapp:equipment' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '4.Financial Assistance for Distribution of Small Tools for Manufacturing of Woolen Items' %}
                            <a href="{% url 'authapp:small_tools_distribution' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '1.Short Term Training Program for Manufacturing and Weaving of Woolen Items' %}
                            <a href="{% url 'authapp:short_term_programme' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '2.On-Site Training for Industrial Workers' %}
                            <a href="{% url 'authapp:onsite_training_progress_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '3.Training on Machine Sheep Shearing' %}
                            <a href="{% url 'authapp:shearing_machine_training_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '4.Research and Development Projects' %}
                            <a href="{% url 'authapp:rd_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '5.International/Domestic Corporations Stakeholders Meeting/Conference' %}
                            <a href="{% url 'authapp:domestic_meeting_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '6.Organizing Seminars, Workshops, Sheep Mela, Fare, Meet' %}
                            <a href="{% url 'authapp:organising_seminar_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '7.Wool Survey and Study on Wool Sector' %}
                            <a href="{% url 'authapp:wool_survey_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '8.Operating Existing Wool Testing Lab at Bikaner Including Upgradation and WDTC/ISC at Kullu' %}
                            <a href="{% url 'authapp:wool_testing_lab_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '9.Publicity of Scheme, Monitoring of Projects, Common Visits, Evaluation of Projects/Schemes, and Awareness Program for Swachhta, etc.' %}
                            <a href="{% url 'authapp:publicity_monitoring_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '1.Revolving fund for pashmina wool marketing (For UT of J&K & UT of Ladakh)' %}
                            <a href="{% url 'authapp:pashmina_revolving_fund_progress_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '2.Setting of machines for pashmina wool processing' %}
                            <a href="{% url 'authapp:pashmina_cfc_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '3.Construction of shelter shed with guard rooms for pashmina goat' %}
                            <a href="{% url 'authapp:shelter_shed_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '4.Distribution of portable tents with accessories' %}
                            <a href="{% url 'authapp:portable_tent_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '5.Distribution of predator-proof corral with LED lights' %}
                            <a href="{% url 'authapp:predator_proof_lights_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '6.Testing equipment, including DNA analyzer for identification/testing of pashmina products' %}
                            <a href="{% url 'authapp:testing_equipment_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '7.Development of showroom at Dehairing Plant premises at Leh' %}
                            <a href="{% url 'authapp:showroom_development_report' proposal.unique_id %}">Submit Report</a>
                        {% elif proposal.scheme_component == '8.Development of fodder land/Govt. farms for pashmina goats' %}
                            <a href="{% url 'authapp:fodder_land_development_report' proposal.unique_id %}">Submit Report</a>
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="5">No Data Found</td>
        </tr>
        {% endif %}
    </table>


{% endblock %}