cwdb_website/authapp/urls.py
from django.urls import path,reverse_lazy

from django.conf import settings
from django.conf.urls.static import static
from . import views

from .views import UserProfileView,EditProfileView,CustomLoginView
app_name = 'authapp'
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

urlpatterns = [
    #HomePage
    path('',views.index,name='index'),
    path('proposal/list/', views.proposal_list, name='proposal_list'),
    path('beneficiary-data/', views.beneficiary_data_table, name='beneficiary_data_table'),
    path('iwdp/', views.iwdp_view, name='iwdp_view'),
    path('wms-data/',views.wms_scheme_view,name='wms_scheme_view'),
    path('wps-data/',views.wps_scheme_view,name='wps_scheme_view'),
    path('pwds-data/',views.pwds_scheme_view,name='pwds_scheme_view'),
    path('hrdpa-data/',views.hrdpa_scheme_view,name='hrdpa_scheme_view'),
    path('admin_Expenses',views.admin_exp_view,name='admin_exp_view'),
     
    path('signup/', views.signup, name='register'),
    
    
    path('notifications/', views.index_notification_view, name='index_notification_view'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),
    # path('login/',user_login,name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/submit_proposal/', views.submit_proposal, name='submit_proposal'),
    path('dashboard/proposal_detail/<int:proposal_id>/', views.proposal_detail, name='proposal_detail'),
    path('dashboard/proposal_list/', views.proposal_list, name='proposal_list'),
    path('dashboard/admin_proposal_list/', views.admin_proposal_list, name='admin_proposal_list'),
    path('dashboard/admin_proposal_detail/<int:proposal_id>/', views.admin_proposal_detail, name='admin_proposal_detail'),
    path('dashboard/proposal_status/', views.proposal_status, name='proposal_status'),
    path('dashboard/proposal_documents/', views.proposal_documents, name='proposal_documents'),
     path('dashboard/sanction-letters/<str:proposal_id>/', views.sanction_letters_view, name='sanction_letters_view'),
    path('dashboard/inspection-letters/<str:proposal_id>/', views.inspection_letters_view, name='inspection_letters_view'),
    path('dashboard/form-submitted/', views.form_submitted_successfully, name='form_submitted_successfully'),

    # path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('login/', CustomLoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='authapp:index'), name='logout'),
    path('admin/logout/',LogoutView.as_view(next_page='authapp:index'), name='logout'),
     path('dashboard/change-password/', PasswordChangeView.as_view(), name='change_password'),
    #proposal admin urls
    path('admin/submit_approval/<str:proposal_id>/', views.submit_approval, name='submit_approval'),
path('admin/submit_installment_sanction_letter/<str:proposal_id>/', views.submit_installment_sanction_letter, name='submit_installment_sanction_letter'),
 path('admin/submit_inspection_report/<str:proposal_id>/', views.submit_inspection_letter, name='submit_inspection_report'),

    # Password Reset URLs
    path('dashboard/forgot-password/', PasswordResetView.as_view(), name='forgot_password'),
    path('dashboard/5/password/', PasswordResetView.as_view(), name='forgot_password'),
    path('dashboard/forgot-password/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('dashboard/reset-password/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('dashboard/reset-password/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # #progress report urls 
    path('dashboard/progress_report/', views.progress_report, name='progress_report'),
    #wms subcomponents
    path('dashboard/revolving_fund_progress_report/<str:proposal_unique_id>/', views.revolving_fund_progress_report, name='revolving_fund_progress_report'),
    path('dashboard/eportal/<str:proposal_unique_id>/', views.eportal_progress_report, name='eportal_progress_report'),
    path('dashboard/selfhelpgroup_report/<str:proposal_unique_id>/', views.selfhelpgroup_report, name='selfhelpgroup_report'),
    path('dashboard/buyersellerexpo_report/<str:proposal_unique_id>/', views.buyersellerexpo_report, name='buyersellerexpo_report'),
    path('dashboard/infrastructuredevelopment_report/<str:proposal_unique_id>/', views.infrastructuredevelopment_report, name='infrastructuredevelopment_report'),
    path('dashboard/woolen_expo/<str:proposal_unique_id>/', views.woolen_expo, name='woolen_expo'),
    path('dashboard/woolen_expo_hiring/<str:proposal_unique_id>/', views.woolen_expo_hiring, name='woolen_expo_hiring'),
    #wps subcomponent
    path('dashboard/cfc_progress_report/<str:proposal_unique_id>/', views.cfc_progress_report, name='cfc_progress_report'),
    path('dashboard/sheep_shearing_machining/<str:proposal_unique_id>/', views.sheep_shearing_machining, name='sheep_shearing_machining'),
    path('dashboard/equipment/<str:proposal_unique_id>/', views.equipment, name='equipment'),
    path('dashboard/small_tools_distribution/<str:proposal_unique_id>/', views.small_tools_distribution, name='small_tools_distribution'),
   # hrd subcomponent
    path('dashboard/short_term_programme/<str:proposal_unique_id>/', views.short_term_programme, name='short_term_programme'),
    path('dashboard/onsite_training_progress_report/<str:proposal_unique_id>/', views.onsite_training_progress_report, name='onsite_training_progress_report'),
    path('dashboard/shearing_machine_training_report/<str:proposal_unique_id>/', views.shearing_machine_training_report, name='shearing_machine_training_report'),
    path('dashboard/rd_report/<str:proposal_unique_id>/', views.rd_report, name='rd_report'),
    path('dashboard/domestic_meeting_report/<str:proposal_unique_id>/', views.domestic_meeting_report, name='domestic_meeting_report'),
    path('dashboard/organising_seminar_report/<str:proposal_unique_id>/', views.organising_seminar_report, name='organising_seminar_report'),
    path('dashboard/wool_survey_report/<str:proposal_unique_id>/', views.wool_survey_report, name='wool_survey_report'),
    path('dashboard/wool_testing_lab_report/<str:proposal_unique_id>/', views.wool_testing_lab_report, name='wool_testing_lab_report'),
    path('dashboard/publicity_monitoring_report/<str:proposal_unique_id>/', views.publicity_monitoring_report, name='publicity_monitoring_report'),
    #pwds subcomponent
    path('dashboard/pashmina_revolving_fund_progress_report/<str:proposal_unique_id>/', views.pashmina_revolving_fund_progress_report, name='pashmina_revolving_fund_progress_report'),
    path('dashboard/pashmina_cfc_report/<str:proposal_unique_id>/', views.pashmina_cfc_report, name='pashmina_cfc_report'),
    path('dashboard/shelter_shed_report/<str:proposal_unique_id>/', views.shelter_shed_report, name='shelter_shed_report'),
    path('dashboard/portable_tent_report/<str:proposal_unique_id>/', views.portable_tent_report, name='portable_tent_report'),
    path('dashboard/predator_proof_lights_report/<str:proposal_unique_id>/', views.predator_proof_lights_report, name='predator_proof_lights_report'),
    path('dashboard/testing_equipment_report/<str:proposal_unique_id>/', views.testing_equipment_report, name='testing_equipment_report'),
    path('dashboard/showroom_development_report/<str:proposal_unique_id>/', views.showroom_development_report, name='showroom_development_report'),
    path('dashboard/fodder_land_development_report/<str:proposal_unique_id>/', views.fodder_land_development_report, name='fodder_land_development_report'),
    #admin
    # urls.py

# path('admin/view_progress_report/<str:proposal_id>/', views.view_progress_report, name='view_progress_report'),
    
#notifications
# path('dashboard/show-notifications/', views.show_notifications, name='show_notifications'),
path('dashboard/show-all-notifications/', views.show_all_notifications, name='show_all_notifications'),
path('dashboard/profile/', UserProfileView.as_view(), name='user_profile'),
path('dashboard/profile/edit/', EditProfileView.as_view(), name='edit_profile'),
# path('dashboard/updated', views.show_notifications, name='show_new_notifications'),
#staff dashboard
path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
path('staff_dashboard/all-proposals/', views.all_proposal_details, name='all_proposal_details'),
path('submit-approval/<str:proposal_id>/', views.submit_approval, name='submit_approval'),
path('generate-summary/<str:proposal_id>/', views.summ_report, name='summ_report'),

#API url
path('apicall/', views.proposal_api),
    
    # Add more patterns as needed

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cwdb_website/src/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import include, path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from authapp.views import index
urlpatterns = [
    path('', include('authapp.urls', namespace='authapp')),
    #  (r'^admin/', include(admin.site.urls) ),
    path('admin/', admin.site.urls),
     # Password Reset URLs
    path('dashboard/forgot-password/', PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='forgot_password'),
    path('dashboard/forgot-password/done/', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('dashboard/reset-password/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('dashboard/reset-password/done/', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    #  path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
     path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change_form.html',
        success_url='password_change_done'
    ), name='change_password'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html'
    ), name='password_change_done'),
]

cwdb_website/templates/all_notifications.html
{% extends 'base_dashboard.html' %}

{% block content %}
<style>
  body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f4f4f4;
  }

  header {
    background-color: #007BFF;
    color: white;
    text-align: center;
    padding: 1em 0;
    margin-bottom: 20px;
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
    border-top-left-radius: 10px;
    border-top-right-radius: 10px;
  }

  h1 {
    margin: 0;
    font-size: 1.5em;
    letter-spacing: 2px;
    text-transform: uppercase;
  }

  .card {
    background-color: #fff;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    border-radius: 8px;
    margin-bottom: 20px;
    padding: 20px;
  }

  .card-title {
    font-size: 1em; /* Smaller font size for date */
    font-weight: bold;
    margin-bottom: 10px;
  }

  .card-content {
    font-size: 1.2em; /* Larger font size for content */
  }

  .no-data {
    text-align: center;
    color: #777;
    padding: 20px;
  }
</style>

<div class="container mt-5">
  <header>
    <h1>All Notifications</h1>
  </header>

  {% if all_notifications %}
    {% for notification in all_notifications %}
      <div class="card">
        <div class="card-title">
          <strong>{{ notification.created_at|date:"F d, Y H:i a" }}</strong>
        </div>
        <div class="card-content">
          {{ notification.message }}
        </div>
      </div>
    {% endfor %}
  {% else %}
    <div class="no-data">
      <p>No notifications found.</p>
    </div>
  {% endif %}
</div>
{% endblock %}

cwdb_website/templates/base_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{%block title%}{%endblock%}</title>

    <!-- Custom fonts for this template-->
    <link href="{%static 'css/user_dashboard/all.min.css'%}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- Custom styles for this template-->
    <link href="{%static 'css/user_dashboard/sb-admin-2.min.css'%}" rel="stylesheet">
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f4f4f4 ;
    }
</style>
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
             <br>
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon rotate-n-15">
                    <!-- <i class="fas fa-laugh-wink"></i> -->
                </div>
                <div>
                </div>
                <div class="sidebar-brand-text mx-sm-2">Central Wool Development Board</div>
            </a>
            <br>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'authapp:dashboard' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>
             <hr class="sidebar-divider my-0">
             <li class="nav-item active">
                <a class="nav-link" href="{% url 'authapp:submit_proposal' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Application Form</span></a>
            </li>
             <hr class="sidebar-divider my-0">
             {% comment %} <li class="nav-item active">
                <a class="nav-link" href="{% url 'authapp:dashboard' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>View Application</span></a>
            </li> {% endcomment %}
             <hr class="sidebar-divider my-0">
             <li class="nav-item active">
                <a class="nav-link" href="{% url 'authapp:proposal_status' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Application Status</span></a>
            </li>
            <hr class="sidebar-divider my-0">
             <li class="nav-item active">
                <a class="nav-link" href="{% url 'authapp:proposal_documents' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>View Documents</span></a>
            </li>
            <hr class="sidebar-divider my-0">
             <li class="nav-item active">
                <a class="nav-link" href="{% url 'authapp:progress_report' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Submit progress</span></a>
            </li>
             {% comment %} <hr class="sidebar-divider my-0">
             <li class="nav-item active">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Feedback/Questions</span></a>
            </li> {% endcomment %}
             <!-- <hr class="sidebar-divider my-0"> -->
            

           

           

          
           

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                 <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow ">  

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                       

                        <!-- your_template.html -->
<li class="nav-item dropdown no-arrow mx-1">
    <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell fa-fw"></i>
        <!-- Counter - Alerts -->
        {% comment %} <span class="badge badge-danger badge-counter">{{ new_notifications.count }}</span> {% endcomment %}
    </a>
    <!-- Dropdown - Alerts -->
    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
        aria-labelledby="alertsDropdown">
        <h6 class="dropdown-header">
            Recent Alerts
        </h6>
        {% for notification in new_notifications %}
            <a class="dropdown-item d-flex align-items-center" href="#">
                <div class="mr-3">
                    <div class="icon-circle bg-primary">
                        <i class="fas fa-file-alt text-white"></i>
                    </div>
                </div>
                <div>
                    <div class="small text-gray-500">{{ notification.created_at|date:"F d, Y H:i a" }}</div>
                    <span class="font-weight-bold">{{ notification.message }}</span>
                </div>
            </a>
        {% endfor %}
        <a class="dropdown-item text-center small text-gray-500" href="{% url 'authapp:show_all_notifications' %}">Show All Alerts</a>
    </div>
</li>


                        <!-- Nav Item - Messages -->
                       
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.email}}</span>
                                <img class="img-profile rounded-circle"
                                    src="{%static 'img/undraw_profile.svg'%}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="{% url 'authapp:user_profile' %}">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="{% url 'change_password' %}">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Change password
                                </a>
                               
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

</nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                   {% block content %}{% endblock %}

                    <!-- Content Row -->
                 

                </div>
                <!-- /.container-fluid -->

           
          
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'authapp:index' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


</body>

</html>