cwdb_website/authapp/urls.py
from django.urls import path,reverse_lazy

from django.conf import settings
from django.conf.urls.static import static
from . import views

from .views import UserProfileView,EditProfileView,CustomLoginView
app_name = 'authapp'
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

urlpatterns = [
    #HomePage
    path('',views.index,name='index'),
    path('proposal/list/', views.proposal_list, name='proposal_list'),
    path('beneficiary-data/', views.beneficiary_data_table, name='beneficiary_data_table'),
    path('iwdp/', views.iwdp_view, name='iwdp_view'),
    path('wms-data/',views.wms_scheme_view,name='wms_scheme_view'),
    path('wps-data/',views.wps_scheme_view,name='wps_scheme_view'),
    path('pwds-data/',views.pwds_scheme_view,name='pwds_scheme_view'),
    path('hrdpa-data/',views.hrdpa_scheme_view,name='hrdpa_scheme_view'),
    path('admin_Expenses',views.admin_exp_view,name='admin_exp_view'),
     
    path('signup/', views.signup, name='register'),
    
    
    path('notifications/', views.index_notification_view, name='index_notification_view'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),
    # path('login/',user_login,name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/submit_proposal/', views.submit_proposal, name='submit_proposal'),
    path('dashboard/proposal_detail/<int:proposal_id>/', views.proposal_detail, name='proposal_detail'),
    path('dashboard/proposal_list/', views.proposal_list, name='proposal_list'),
    path('dashboard/admin_proposal_list/', views.admin_proposal_list, name='admin_proposal_list'),
    path('dashboard/admin_proposal_detail/<int:proposal_id>/', views.admin_proposal_detail, name='admin_proposal_detail'),
    path('dashboard/proposal_status/', views.proposal_status, name='proposal_status'),
    path('dashboard/proposal_documents/', views.proposal_documents, name='proposal_documents'),
     path('dashboard/sanction-letters/<str:proposal_id>/', views.sanction_letters_view, name='sanction_letters_view'),
    path('dashboard/inspection-letters/<str:proposal_id>/', views.inspection_letters_view, name='inspection_letters_view'),
    path('dashboard/form-submitted/', views.form_submitted_successfully, name='form_submitted_successfully'),

    # path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('login/', CustomLoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='authapp:index'), name='logout'),
    path('admin/logout/',LogoutView.as_view(next_page='authapp:index'), name='logout'),
     path('dashboard/change-password/', PasswordChangeView.as_view(), name='change_password'),
    #proposal admin urls
    path('admin/submit_approval/<str:proposal_id>/', views.submit_approval, name='submit_approval'),
path('admin/submit_installment_sanction_letter/<str:proposal_id>/', views.submit_installment_sanction_letter, name='submit_installment_sanction_letter'),
 path('admin/submit_inspection_report/<str:proposal_id>/', views.submit_inspection_letter, name='submit_inspection_report'),

    # Password Reset URLs
    path('dashboard/forgot-password/', PasswordResetView.as_view(), name='forgot_password'),
    path('dashboard/5/password/', PasswordResetView.as_view(), name='forgot_password'),
    path('dashboard/forgot-password/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('dashboard/reset-password/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('dashboard/reset-password/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # #progress report urls 
    path('dashboard/progress_report/', views.progress_report, name='progress_report'),
    #wms subcomponents
    path('dashboard/revolving_fund_progress_report/<str:proposal_unique_id>/', views.revolving_fund_progress_report, name='revolving_fund_progress_report'),
    path('dashboard/eportal/<str:proposal_unique_id>/', views.eportal_progress_report, name='eportal_progress_report'),
    path('dashboard/selfhelpgroup_report/<str:proposal_unique_id>/', views.selfhelpgroup_report, name='selfhelpgroup_report'),
    path('dashboard/buyersellerexpo_report/<str:proposal_unique_id>/', views.buyersellerexpo_report, name='buyersellerexpo_report'),
    path('dashboard/infrastructuredevelopment_report/<str:proposal_unique_id>/', views.infrastructuredevelopment_report, name='infrastructuredevelopment_report'),
    path('dashboard/woolen_expo/<str:proposal_unique_id>/', views.woolen_expo, name='woolen_expo'),
    path('dashboard/woolen_expo_hiring/<str:proposal_unique_id>/', views.woolen_expo_hiring, name='woolen_expo_hiring'),
    #wps subcomponent
    path('dashboard/cfc_progress_report/<str:proposal_unique_id>/', views.cfc_progress_report, name='cfc_progress_report'),
    path('dashboard/sheep_shearing_machining/<str:proposal_unique_id>/', views.sheep_shearing_machining, name='sheep_shearing_machining'),
    path('dashboard/equipment/<str:proposal_unique_id>/', views.equipment, name='equipment'),
    path('dashboard/small_tools_distribution/<str:proposal_unique_id>/', views.small_tools_distribution, name='small_tools_distribution'),
   # hrd subcomponent
    path('dashboard/short_term_programme/<str:proposal_unique_id>/', views.short_term_programme, name='short_term_programme'),
    path('dashboard/onsite_training_progress_report/<str:proposal_unique_id>/', views.onsite_training_progress_report, name='onsite_training_progress_report'),
    path('dashboard/shearing_machine_training_report/<str:proposal_unique_id>/', views.shearing_machine_training_report, name='shearing_machine_training_report'),
    path('dashboard/rd_report/<str:proposal_unique_id>/', views.rd_report, name='rd_report'),
    path('dashboard/domestic_meeting_report/<str:proposal_unique_id>/', views.domestic_meeting_report, name='domestic_meeting_report'),
    path('dashboard/organising_seminar_report/<str:proposal_unique_id>/', views.organising_seminar_report, name='organising_seminar_report'),
    path('dashboard/wool_survey_report/<str:proposal_unique_id>/', views.wool_survey_report, name='wool_survey_report'),
    path('dashboard/wool_testing_lab_report/<str:proposal_unique_id>/', views.wool_testing_lab_report, name='wool_testing_lab_report'),
    path('dashboard/publicity_monitoring_report/<str:proposal_unique_id>/', views.publicity_monitoring_report, name='publicity_monitoring_report'),
    #pwds subcomponent
    path('dashboard/pashmina_revolving_fund_progress_report/<str:proposal_unique_id>/', views.pashmina_revolving_fund_progress_report, name='pashmina_revolving_fund_progress_report'),
    path('dashboard/pashmina_cfc_report/<str:proposal_unique_id>/', views.pashmina_cfc_report, name='pashmina_cfc_report'),
    path('dashboard/shelter_shed_report/<str:proposal_unique_id>/', views.shelter_shed_report, name='shelter_shed_report'),
    path('dashboard/portable_tent_report/<str:proposal_unique_id>/', views.portable_tent_report, name='portable_tent_report'),
    path('dashboard/predator_proof_lights_report/<str:proposal_unique_id>/', views.predator_proof_lights_report, name='predator_proof_lights_report'),
    path('dashboard/testing_equipment_report/<str:proposal_unique_id>/', views.testing_equipment_report, name='testing_equipment_report'),
    path('dashboard/showroom_development_report/<str:proposal_unique_id>/', views.showroom_development_report, name='showroom_development_report'),
    path('dashboard/fodder_land_development_report/<str:proposal_unique_id>/', views.fodder_land_development_report, name='fodder_land_development_report'),
    #admin
    # urls.py

# path('admin/view_progress_report/<str:proposal_id>/', views.view_progress_report, name='view_progress_report'),
    
#notifications
# path('dashboard/show-notifications/', views.show_notifications, name='show_notifications'),
path('dashboard/show-all-notifications/', views.show_all_notifications, name='show_all_notifications'),
path('dashboard/profile/', UserProfileView.as_view(), name='user_profile'),
path('dashboard/profile/edit/', EditProfileView.as_view(), name='edit_profile'),
# path('dashboard/updated', views.show_notifications, name='show_new_notifications'),
#staff dashboard
path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
path('staff_dashboard/all-proposals/', views.all_proposal_details, name='all_proposal_details'),
path('submit-approval/<str:proposal_id>/', views.submit_approval, name='submit_approval'),
path('generate-summary/<str:proposal_id>/', views.summ_report, name='summ_report'),

#API url
path('apicall/', views.proposal_api),
    
    # Add more patterns as needed

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cwdb_website/src/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import include, path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from authapp.views import index
urlpatterns = [
    path('', include('authapp.urls', namespace='authapp')),
    #  (r'^admin/', include(admin.site.urls) ),
    path('admin/', admin.site.urls),
     # Password Reset URLs
    path('dashboard/forgot-password/', PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='forgot_password'),
    path('dashboard/forgot-password/done/', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('dashboard/reset-password/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('dashboard/reset-password/done/', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    #  path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
     path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change_form.html',
        success_url='password_change_done'
    ), name='change_password'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html'
    ), name='password_change_done'),
]

cwdb_website/templates/main/dashboard.html
{% extends 'base_dashboard.html' %}
{% block title %}Dashboard{% endblock %}
{%block content%}


    <!-- Page Heading -->
  

    <!-- Content Row -->
    <div class="row">

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Proposal Submitted</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{submitted_proposals_count}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Proposal Approved</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{approved_proposals_count}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                                Proposal Pending</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{pending_proposals_count}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <!-- <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Proposal Reject
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">0</div>
                                </div>
                                 <div class="col-auto">
                            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                        </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div> -->

        <!-- Pending Requests Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                Proposal Rejected</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{rejected_proposals_count}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    

    
  

   

{% endblock %}

cwdb_website/templates/main/form_submitted_sucessfully.html
<!-- form_submitted_successfully.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form Submitted Successfully</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        
        .card {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            padding: 20px;
            width: 300px;
            text-align: center;
        }
        
        h1 {
            color: #333;
        }
        
        p {
            color: #666;
            margin-bottom: 20px;
        }
        
        .btn {
            display: inline-block;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 4px;
            transition: background-color 0.3s;
            margin-right: 10px;
            margin-bottom: 10px; /* Added margin bottom */
        }
        
        .btn:last-child {
            margin-right: 0; /* Remove margin right for the last button */
        }
        
        .btn:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="card">
        <h1>Form Submitted Successfully!</h1>
        <p>Your form has been submitted successfully.</p>
        <a href="{% url 'authapp:dashboard' %}" class="btn">Go back to dashboard</a>
        <a href="{% url 'authapp:logout' %}" class="btn">Logout</a>
    </div>
</body>
</html>